
--CRIANDO A TABELA DE PRODUTOS

USE SUCOS;

CREATE TABLE TB_PRODUTOS
(CODIGO_PRODUTO VARCHAR(50),
 NOME_PRODUTO VARCHAR(150),
 EMBALAGEM VARCHAR(50),
 TAMANHO VARCHAR(50),
 SABOR VARCHAR(50),
 PRECO_LISTA FLOAT);