
--INSIRA OS SEGUINTES DADOS NA TABELA TB_PRODUTOS: 
--CÓDIGO DO PROTUDO: 1040107;
--NOME DO PRODUTO: LIGHT - 350ML - MELÂNCIA;
--EMBALAGEM: LATA;
--TAMANHO: 350ML
--SABOR: MELÂNCIA
--PRECO_LISTA: R$: 4,56

USE SUCOS;

INSERT INTO TB_PRODUTOS (
    CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
    VALUES ('1040107', 'LIGHT - 350ML - MELÂNCIA', 'LATA', '350ML', 'MELÂNCIA', 4.56);

SELECT * FROM tb_produtos;

--INSIRA OS SEGUINTES DADOS NA TABELA TB_PRODUTOS: 
--CÓDIGO DO PROTUDO: 1037797;
--NOME DO PRODUTO: Clean - 2 Litros - Laranja;
--EMBALAGEM: Pet;
--TAMANHO: 2 Litros
--SABOR: Laranja
--PRECO_LISTA: R$: 16,01

USE SUCOS;

INSERT INTO TB_PRODUTOS (
    CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) 
    VALUES ('1037797', 'Clean - 2 Litros - Laranja', 'Pet', '2 Litros', 'Laranja', 16.01); 

SELECT * FROM tb_produtos

--INSIRA OS SEGUINTES DADOS NA TABELA TB_PRODUTOS: 
--CÓDIGO DO PROTUDO: 1000889;
--NOME DO PRODUTO: Sabor da Montanha - 700 ml - Uva;
--EMBALAGEM: Garrafa;
--TAMANHO: 700 ml;
--SABOR: Uva;
--PRECO_LISTA: R$: 6,31

USE SUCOS;

INSERT INTO TB_PRODUTOS (
    CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) 
    VALUES ('1000889', 'Sabor da Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31);

SELECT * FROM tb_produtos

--INSIRA OS SEGUINTES DADOS NA TABELA TB_PRODUTOS: 
--CÓDIGO DO PROTUDO: 1004327;
--NOME DO PRODUTO: Videira do Campo - 1,5 Litros - Melância;
--EMBALAGEM: Pet;
--TAMANHO: 1,5 Litros;
--SABOR: Melância;
--PRECO_LISTA: R$: 19,51

USE SUCOS;

INSERT INTO TB_PRODUTOS (
    CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) 
    VALUES ('1004327', 'Videira do Campo - 1,5 Litros - Melância', 'Pet', '1,5 Litros', 'Melância', 19.51);

SELECT * FROM tb_produtos

--INSIRA OS SEGUINTES DADOS NA TABELA TB_PRODUTOS: 
--CÓDIGO DO PROTUDO: 544931;
--NOME DO PRODUTO: Frescor do Verão - 350 ml - Limão;
--EMBALAGEM: Pet;
--TAMANHO: 350 ml;
--SABOR: Limão;
--PRECO_LISTA: R$: 3,20

USE SUCOS; 

INSERT INTO TB_PRODUTOS (
    CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) 
    VALUES ('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml', 'Limão', 3.20);

--VALIDAÇÃO SE HOUVE ALTERAÇÃO NA TABELA
SELECT * FROM tb_produtos;

--INSIRA OS SEGUINTES DADOS NA TABELA TB_PRODUTOS: 
--CÓDIGO DO PROTUDO: 1078680;
--NOME DO PRODUTO: Frescor do Verão - 470 ml - Manga;
--EMBALAGEM: Lata;
--TAMANHO: 470 ml;
--SABOR: Manga;
--PRECO_LISTA: R$: 5,18

USE SUCOS; 

INSERT INTO TB_PRODUTOS (
    CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) 
    VALUES ('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml', 'Manga', 5.18);

--VALIDAÇÃO SE HOUVE ALTERAÇÃO NA TABELA
SELECT * FROM tb_produtos;

