
--CRIE UMA SEGUNDA TABELA DE VENDEDORES: 

USE SUCOS;

CREATE TABLE TABELA_DE_VENDEDORES2 (
    MATRICULA VARCHAR(5),
    NOME VARCHAR(100),
    PERCENTUAL_COMISSAO FLOAT
)

--CHECANDO SE A TABELA FOI CRIADA
SELECT * FROM TABELA_DE_VENDEDORES2

--APAGUE A SEGUNDA TABELA DE VENDEDORES UTILIZANDO O COMANDO DROP TABLE:
DROP TABLE TABELA_DE_VENDEDORES2

--VALIDAÇÃO SE HOUVE FOI APAGADA A TABELA
SELECT * FROM TABELA_DE_VENDEDORES2