
--A VENDEDORA CLÁUDIA (00236) CONSEGUIU UM AUMENTO NO PERCENTUAL DE VENDAS PARA 11%. POR FAVOR, REALIZE A MODIFICAÇÃO NO BANCO DE DADOS. 

USE SUCOS;

UPDATE TABELA_DE_VENDEDORES SET PERCENTUAL_COMISSAO = 0.11
WHERE MATRICULA = '00236';

--VALIDAÇÃO DA MODIFICAÇÃO SOLICITADA
SELECT PERCENTUAL_COMISSAO FROM TABELA_DE_VENDEDORES
WHERE MATRICULA '00236'


--JOSÉ GERALDO DA FONSECA (00233) RECLAMOU QUE SEU NOME REAL É JOSÉ GERALDO DA FONSECA JUNIOR.

USE SUCOS;

UPDATE TABELA_DE_VENDEDORES SET NAME = 'José Geraldo da Fonseca Junior'
WHERE MATRICULA = '00233';

--VALIDAÇÃO DA MODIFICAÇÃO SOLICITADA
SELECT NAME FROM TABELA_DE_VENDEDORES
WHERE MATRICULA = '00233';

--O VENDEDOR JOSÉ GERALDO DA FONSECA JUNIOR MATRÍCULA (00233), FOI DEMITIDO. RETIRE-O DA TABELA DE VENDEDORES.

USE SUCOS;

DELETE FROM TABELA_DE_VENDEDORES
WHERE MATRICULA = '00233';

--VALIDANDO SE O VENDEDOR FOI DELETADO DA TABELA
SELECT * FROM TABELA_DE_VENDEDORES;

--VAMOS INCLUIR NOVOS CAMPOS NA TABELA DE VENDEDORES. ELES SERÃO A DATA DE ADMISSÃO
--SE O VENDEDOR ESTÁ DE FÉRIAS OU NÃO

ALTER TABLE TABELA_DE_VENDEDORES ADD COLUMN (DATA_ADMISSAO DATE);
ALTER TABLE TABELA_DE_VENDEDORES ADD COLUMN (DE_FERIAS BIT(1));

--VALIDANDO UPDATES NA TABELA DE VENDEDORES
SELECT DATA_ADMISSAO, DE_FERIAS, NAME FROM TABELA_DE_VENDEDORES

--ADICIONE UMA CHAVE PRIMARIA NO CAMPO (MATRICULA) DA TABELA DE VENDEDORES

ALTER TABLE TABELA_DE_VENDEDORES ADD PRIMARY KEY (MATRICULA);

--FAÇA AS SEGUINTES MODIFICAÇÕES: 

--MATRICULA: 00235
--DATA_ADMISSAO: 15/08/2014
--DE_FERIA: NÃO

--MATRICULA: 00236
--DATA_ADMISSAO:17/09/2013
--DE_FERIAS: SIM

--MATRICULA: 00237
--DATA_ADMISSAO:18/03/2017
--DE_FERIAS: SIM

--MATRICULA: 00238
--DATA_ADMISSAO:21/08/2016
--DE_FERIAS: NÃO

UPDATE TABELA_DE_VENDEDORES SET DATA_ADMISSAO = '2014-08-15', DE_FERIAS = 0
WHERE MATRICULA = 00235

UPDATE TABELA_DE_VENDEDORES SET DATA_ADMISSAO = '2013-09-17', DE_FERIAS = 1
WHERE MATRICULA = 00236 

UPDATE TABELA_DE_VENDEDORES SET DATA_ADMISSAO = '2017-03-18', DE_FERIAS = 1
WHERE MATRICULA = 00237

UPDATE TABELA_DE_VENDEDORES SET DATA_ADMISSAO = '2016-08-21', DE_FERIAS = 0
WHERE MATRICULA = 00238

--VALIDAÇÃO DAS UPDATES REALIZADA NA TABELA DE VENDEDORES
SELECT DATA_ADMISSAO, DE_FERIAS, NOME FROM TABELA_DE_VENDEDORES

--SELECIONE O NOME E MATRICULA DE TODOS OS VENDEDORES
SELECT NOME, MATRICULA FROM tabela_de_vendedores;

--VERIFIQUE OS DADOS CADASTRAIS DA VENDEDORA CLÁUDIA MORAIS
SELECT * FROM TABELA_DE_VENDEDORES
WHERE NOME = 'CLÁUDIA MORAIS';

--VEJA QUAIS SÃO OS VENDEDORES QUE POSSUEM COMISSÃO MAIOR QUE 10% 
SELECT * FROM TABELA_DE_VENDEDORES
WHERE PERCENTUAL_COMISSAO >= 0.10;

--VEJA QUAIS SÃO OS VENDEDORES ADMITIDOS NA EMPRESA A PARTIR DE 2016
SELECT * FROM TABELA_DE_VENDEDORES
WHERE YEAR (DATA_ADMISSAO) >= 2016;

--VEJA QUAIS SÃO OS VENDEDORES QUE ESTÃO DE FÉRIAS E FORAM ADMITIDOS ANTES DE 2016
SELECT * FROM TABELA_DE_VENDEDORES
WHERE YEAR (DATA_ADMISSAO) <= 2016 AND DE_FERIAS = 1;

